# travis.yml

os: linux
language: C

addons:
  apt:
    packages:
      - lua5.4.2
      - npm

before_script:
  - npm i love.js

script: "make web"


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: LD48Compo
  local_dir: "build/game"
